set(CMAKE_GENERATOR "Unix Makefiles" CACHE INTERNAL "" FORCE)

set(CMAKE_BUILD_TYPE "Debug" CACHE INTERNAL "" FORCE)
# set(CMAKE_BUILD_TYPE "Release" CACHE INTERNAL "" FORCE)

# set(CMAKE_C_COMPILER "clang" CACHE INTERNAL "" FORCE)
# set(CMAKE_CXX_COMPILER "clang++" CACHE INTERNAL "" FORCE)
