set(PROJECT_INCLUDE_DIRS ${PROJECT_INCLUDE_DIRS}
    ${PROJECT_SOURCE_DIR}/dio32srv
)
set(PROJECT_INCLUDES ${PROJECT_INCLUDES}
    ${PROJECT_SOURCE_DIR}/dio32srv/Dio32InRegs.h
    ${PROJECT_SOURCE_DIR}/dio32srv/Dio32InSrv.h
    ${PROJECT_SOURCE_DIR}/dio32srv/Dio32OutRegs.h
    ${PROJECT_SOURCE_DIR}/dio32srv/Dio32OutSrv.h
)
set(PROJECT_SOURCES ${PROJECT_SOURCES}
    ${PROJECT_SOURCE_DIR}/dio32srv/Dio32InSrv.cpp
    ${PROJECT_SOURCE_DIR}/dio32srv/Dio32OutSrv.cpp
)
